spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/defi_stat}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

app:
  merkl:
    baseUrl: https://api.merkl.xyz    # V4 API
    enabled: true
    timeoutMs: 5000
  euler:
    eulerscan:
      baseUrl: https://api.eulerscan.xyz
      # сеть → chain-параметр EulerScan
      chainMap:
        avalanche: avax
        avax: avax
        base: base
        ethereum: ethereum
        arbitrum: arb
  network:
    avalanche:
      chainId: 43114
      rpcUrls:
        - https://api.avax.network/ext/bc/C/rpc
      utilsLens: "0x37E873e98480a4D18711eb326F5A8F1A31C43FE6"
      subgraph:
        url: "https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-v2-avalanche/latest/gn"
      polling:
        cron: "0 0/15 * * * ?"  # every 10 minutes
    base:
      chainId: 8453
      rpcUrls:
        - https://base.drpc.org
        - https://base.llamarpc.com
        - https://mainnet.base.org
        - https://base-mainnet.infura.io/v3/${INFURA_API_KEY:XXXX}
      utilsLens: "0xE055Fa087e836efAcaFa257e5F6CF90936c26Cb5"
      subgraph:
        url: "https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-v2-base/latest/gn"
      polling:
        cron: "0 0/20 * * * ?"  # every 20 minutes
    ethereum:
        rpcUrls: ${EULER_RPC_URL_MAINNET:https://eth.llamarpc.com}
        subgraph:
          url: "https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-v2-mainnet/latest/gn"

  calc:
    liquidationThresholdPct: 83
    priceCollateralUSD: 1.0
    priceBorrowUSD: 1.0
